### ISSUE TITLE
How to parse MessageRaw struct.

### ISSUE THREAD

**Issue by ben-crowhurst** [aler9/gomavlib#4]
Question, how is it recommended to parse MessageRaw struct without knowledge of the version?

**Recent Change**
https://github.com/aler9/gomavlib/commit/596af81cb7549f11f1e75a9584ac99bd127f2682#diff-f6846c341ab11ff34eeb7463ce2816ff

**Code**
``` golang
	var fault error
	state.peer, fault = gomavlib.NewNode(gomavlib.NodeConf{
		OutSystemId:      255,
		HeartbeatDisable: true,
		Endpoints:        []gomavlib.EndpointConf{endpoint},
	})
	exitOnError(peerConnectionFailed, fault)
	defer state.peer.Close()
```
**Output**
```
OutVersion not provided
```

**Comment by aler9** [comment]
Hi, i was forced to make OutVersion mandatory, since there are some people that want to use this library with Ardupilot (Mavlink V1), and some others with PX4 (Mavlink V2). Just set OutVersion:

```go
	var fault error
	state.peer, fault = gomavlib.NewNode(gomavlib.NodeConf{
		OutSystemId:      255,
                OutVersion: gomavlib.V2,
		HeartbeatDisable: true,
		Endpoints:        []gomavlib.EndpointConf{endpoint},
	})
	exitOnError(peerConnectionFailed, fault)
	defer state.peer.Close()
```

Sorry for the change, just use go get / go.mod / go.sum to download a specific revision of the library and keep it forever, unless something doesn't work.
